### ISSUE TITLE
tf1

### ISSUE THREAD

**Issue by campones** [Paradise-91/ParaTV#3]
salut

les streams de tf1 ne sont plus actualisés.

**Comment by Paradise91D4** [comment]
fixed

**Comment by campones** [comment]
merci

**Comment by campones** [comment]
salut, 

pareil plus actualisés,  je reçois un 403 forbidden

merci

**Comment by Paradise91D4** [comment]
C'est corrigé, désolé.

**Comment by campones** [comment]
salut
c'est marrant tous les streams ont été mis a jour a part celui de tf1 justement

**Comment by Paradise91D4** [comment]
Ça devrait être bon. Ils ont fait un changement uniquement sur TF1. J'ai corrigé, mais cela peut se casser à nouveau s'il y a un nouveau changement. N'hésitez pas à me le signaler ici. Bonne soirée.

**Comment by campones** [comment]
merci bonne soirée également
