### ISSUE TITLE
France 2/3/4/5 cassées

### ISSUE THREAD

**Issue by jcn50** [Paradise-91/ParaTV#6]
Les chaînes ne marchent plus :(

**Comment by Paradise91D4** [comment]
De mon côté, il n'y a aucun souci avec les streams. J'ai testé avec deux adresses IP différentes et tout fonctionne correctement.

Assurez-vous que votre lecteur utilise un user agent pour les chaînes France TV. Si votre lecteur ne supporte pas le paramètre déjà intégré dans mes playlists, veuillez ajouter le user agent dans les paramètres de votre lecteur
